smtp:
  server:
    addr: ":21025"
    domain: "shieldemail.ddns.net"
    read_timeout_seconds: 10
    write_timeout_seconds: 10
    max_message_bytes: 1024
    max_recipients: 50
    allow_insecure_auth: true

  client: {}

telegram:
  token: "your_Bot_token"
  debug: false

rabbitmq:
  dsn: "amqp://guest:guest@localhost:5672/"

database:
  hostname: "localhost"
  port: 27017
  username: "root"
  password: "example"